"""Render chapter pages (Markdown + standalone SVG schematics) under corpora/."""

from collections import Counter
from pathlib import Path

import yaml

from .fingerprints import COMPONENTS
from .model import Chapter, Corpus
from .svgflow import kinds_used, render_lane
from .translation import mode_status

MAX_MINI_BADGES = 5

# (state, display label) in report order; "fallback" reads as "auto" for humans.
SCHEMATIC_STATES = [("ok", "ok"), ("stale", "stale"), ("fallback", "auto"), ("none", "none")]
FACTS_STATES = [("ok", "ok"), ("stale", "stale"), ("none", "none")]

PROVIDER_LABELS = {"ollama": "Ollama", "openai": "OpenAI", "anthropic": "Anthropic"}

GENERATED_NOTE = (
    "<!-- Generated by `uv run python -m tools.notes` — do not edit by hand; "
    "curate via corpora/<corpus>/<vN>/data/flows.yaml and --set-facts. -->"
)


def state_summary(counts: Counter, states: list[tuple[str, str]]) -> str:
    """'40 ok, 2 stale' — omits zero-count states."""
    return ", ".join(f"{counts[s]} {label}" for s, label in states if counts[s])


def flow_entry_for(chapter: Chapter) -> dict | None:
    if chapter.flow and chapter.flow.get("flows"):
        return chapter.flow
    return chapter.fallback_flow


def svg_relpaths(chapter: Chapter) -> list[str]:
    """Paths of the chapter's lane SVGs, relative to the corpora/ root."""
    entry = flow_entry_for(chapter)
    lanes = entry["flows"] if entry else []
    return [
        f"{chapter.corpus}/{chapter.register}/notes/{chapter.group}/assets/"
        f"{chapter.slug}-flow-{i}.svg"
        for i in range(1, len(lanes) + 1)
    ]


def _frontmatter(chapter: Chapter, checkout: str) -> str:
    fm: dict = {
        "id": chapter.id,
        "corpus": chapter.corpus,
        "register": chapter.register,
        "group": chapter.group,
        "group_label": chapter.group_label,
        "number": chapter.number,
        "slug": chapter.slug,
        "title": chapter.short_title,
    }
    if chapter.description:
        fm["description"] = chapter.description
    if chapter.time_cost:
        fm["time"] = chapter.time_cost
    fm["lab"] = chapter.lab_slug
    if chapter.lab_deps:
        fm["lab_deps"] = chapter.lab_deps
    fm["components"] = chapter.components
    if not chapter.concept_only:
        fm["providers"] = chapter.providers
    fm["content_hash"] = chapter.content_hash
    fm["schematic"] = chapter.schematic_state
    fm["facts"] = chapter.facts_state
    if chapter.doc_url:
        fm["doc_url"] = chapter.doc_url
    if chapter.doc_source_url:
        fm["doc_source"] = chapter.doc_source_url
    if chapter.lab_slug:
        fm["lab_source"] = chapter.lab_source_url
    fm["source_checkout"] = checkout
    body = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, width=1000)
    return f"---\n{body}---"


def _callout(chapter: Chapter) -> list[str]:
    if chapter.schematic_state == "ok" and chapter.facts_state == "ok":
        return []
    items = []
    if chapter.facts_state == "none":
        items.append(
            f"**Key facts:** not yet authored. Run `/update-notes {chapter.id}`."
        )
    elif chapter.facts_state == "stale":
        items.append(
            f"**Key facts:** the chapter changed since these facts were authored. "
            f"Re-author via `/update-notes {chapter.id}`, or review and run "
            f"`uv run python -m tools.notes --accept-drift {chapter.id}`."
        )
    if chapter.schematic_state == "stale":
        items.append(
            f"**Schematic:** the chapter changed since its flow was curated. Review "
            f"the flow, then run `uv run python -m tools.notes --accept-drift {chapter.id}`."
        )
    elif chapter.schematic_state == "fallback":
        items.append(
            "**Schematic:** auto-converted from the chapter's Mermaid diagram; "
            f"no curated entry in `corpora/{chapter.corpus}/{chapter.register}/data/flows.yaml` yet."
        )
    elif chapter.schematic_state == "none":
        items.append(
            f"**Schematic:** none curated for this chapter yet. Add a `{chapter.local_id}` "
            f"entry to `corpora/{chapter.corpus}/{chapter.register}/data/flows.yaml` and re-run."
        )
    return ["> [!WARNING]", *(f"> - {item}" for item in items), ""]


def _chapter_markdown(chapter: Chapter, checkout: str, has_labs: bool) -> str:
    out = [_frontmatter(chapter, checkout), GENERATED_NOTE, ""]

    out += [f"# {chapter.short_title}", ""]
    meta = [f"**{chapter.group_label}** · Chapter {chapter.number}"]
    if chapter.time_cost:
        meta.append(chapter.time_cost)
    if chapter.concept_only and has_labs:
        meta.append("Concept chapter · no lab")
    out += [" · ".join(meta), ""]
    if chapter.description:
        out += [f"*{chapter.description}*", ""]

    out += _callout(chapter)

    out += ["## Key facts", ""]
    if chapter.facts:
        out += [f"**{chapter.facts['takeaway']}**", ""]
        for sec in chapter.facts["sections"]:
            out += [f"### {sec['heading']}", ""]
            out += [f"- {point}" for point in sec["points"]]
            out.append("")
    else:
        out += ["No key facts authored for this chapter yet.", ""]

    out += ["## Components", ""]
    if chapter.components:
        out += [
            f"- **{COMPONENTS[c][0]}** — {COMPONENTS[c][1]}" for c in chapter.components
        ]
    else:
        out.append("No components detected.")
    out.append("")

    entry = flow_entry_for(chapter)
    if entry:
        out += ["## Schematic", ""]
        for i, lane in enumerate(entry["flows"], start=1):
            out += [
                f"### {lane['name']}",
                "",
                f"![{lane['name']}](assets/{chapter.slug}-flow-{i}.svg)",
                "",
            ]
        legend = kinds_used(entry)
        if legend:
            out += [f"*Legend: {' · '.join(legend)}*", ""]

    if not chapter.concept_only:
        out += ["## Providers", ""]
        out += [
            " · ".join(
                PROVIDER_LABELS[p] if p in chapter.providers else f"~~{PROVIDER_LABELS[p]}~~"
                for p in ("ollama", "openai", "anthropic")
            ),
            "",
        ]

    source_lines = []
    if chapter.doc_url:
        line = f"- Chapter: [{chapter.doc_url.removeprefix('https://')}]({chapter.doc_url})"
        if chapter.doc_source_url:
            line += f" ([source]({chapter.doc_source_url}))"
        source_lines.append(line)
    elif chapter.doc_source_url:
        source_lines.append(
            f"- Chapter source: "
            f"[{chapter.doc_source_url.removeprefix('https://')}]({chapter.doc_source_url})"
        )
    if chapter.lab_slug:
        source_lines.append(
            f"- Lab: [labs/{chapter.group}/{chapter.lab_slug}]({chapter.lab_source_url})"
        )
    if chapter.lab_deps:
        source_lines.append(
            "- Lab dependencies: " + " ".join(f"`{d}`" for d in chapter.lab_deps)
        )
    if source_lines:
        out += ["## Sources", "", *source_lines, ""]

    if chapter.mermaid:
        out += [
            "<details>",
            "<summary>Original chapter diagram (Mermaid source)</summary>",
            "",
            "```mermaid",
            chapter.mermaid.rstrip(),
            "```",
            "",
            "</details>",
            "",
        ]
    if chapter.readme_flow:
        out += [
            "<details>",
            "<summary>Lab README: what the script is actually doing</summary>",
            "",
            chapter.readme_flow.rstrip(),
            "",
            "</details>",
            "",
        ]

    return "\n".join(out).rstrip() + "\n"


def _table_cell(text: str) -> str:
    return text.replace("|", "\\|")


def _index_markdown(corpus: Corpus) -> str:
    """Per-register index at corpora/<name>/<vN>/notes/README.md; links are
    relative to that file. The cross-corpus overview is the web viewer's index."""
    chapters = corpus.chapters
    sch = state_summary(Counter(c.schematic_state for c in chapters), SCHEMATIC_STATES)
    fac = state_summary(Counter(c.facts_state for c in chapters), FACTS_STATES)
    labs = sum(1 for c in chapters if not c.concept_only)
    label = f": {corpus.label}" if corpus.label else ""
    modes = " · ".join(
        m + ("" if mode_status(m) == "implemented" else " (recorded — not yet rendered)")
        for m in corpus.modes
    )
    out = [
        f"# {corpus.title} — Notes ({corpus.register}{label})",
        "",
        GENERATED_NOTE,
        "",
        f"{len(chapters)} chapters · {labs} labs · key facts: {fac} · schematics: {sch}.",
        "",
    ]
    if modes:
        out += [f"Translation modes: {modes}.", ""]
    for group in corpus.groups:
        group_chapters = [c for c in chapters if c.group == group.id]
        if not group_chapters:
            continue
        out += [
            f"## {group.label}",
            "",
            "| # | Chapter | Key facts | Schematic | Components |",
            "|---|---------|-----------|-----------|------------|",
        ]
        for c in group_chapters:
            badges = [COMPONENTS[comp][0] for comp in c.components[:MAX_MINI_BADGES]]
            if len(c.components) > MAX_MINI_BADGES:
                badges.append(f"+{len(c.components) - MAX_MINI_BADGES}")
            if c.concept_only and corpus.has_labs:
                badges.append("concept")
            out.append(
                f"| {c.number} "
                f"| [{_table_cell(c.short_title)}]({c.group}/{c.slug}.md) "
                f"| {c.facts_state} | {c.schematic_state} "
                f"| {_table_cell(', '.join(badges))} |"
            )
        out.append("")
    out += [
        f"*Generated by `uv run python -m tools.notes` from "
        f"{corpus.name}/{corpus.register}@{corpus.checkout}.*",
        "",
    ]
    return "\n".join(out)


def render_all(
    corpora: list[Corpus],
    out_dir: Path,
    only: set[str] | None = None,
) -> list[Path]:
    written: list[Path] = []
    for corpus in corpora:
        for chapter in corpus.chapters:
            if only and chapter.id not in only:
                continue
            page = out_dir / chapter.page_relpath
            page.parent.mkdir(parents=True, exist_ok=True)
            page.write_text(_chapter_markdown(chapter, corpus.checkout, corpus.has_labs))
            written.append(page)

            entry = flow_entry_for(chapter)
            if entry:
                assets = page.parent / "assets"
                assets.mkdir(parents=True, exist_ok=True)
                for i, lane in enumerate(entry["flows"], start=1):
                    svg = assets / f"{chapter.slug}-flow-{i}.svg"
                    svg.write_text(
                        render_lane(
                            lane,
                            uid=f"{chapter.corpus}-{chapter.register}-"
                                f"{chapter.group}-{chapter.number}-{i}",
                        ) + "\n"
                    )
                    written.append(svg)

        index = out_dir / corpus.name / corpus.register / "notes" / "README.md"
        index.parent.mkdir(parents=True, exist_ok=True)
        index.write_text(_index_markdown(corpus))
        written.append(index)
    return written
