"use client";

// Keyboard reference, opened with "?" or from the status bar.

const BINDINGS: [keys: string, action: string][] = [
  ["⌘K · ⌘P · /", "go to anything (chapters, surfaces, terms)"],
  ["⌘B · b", "toggle explorer"],
  ["⌘J · c", "toggle coach"],
  ["j · k", "move selection in the explorer tree"],
  ["h · l", "collapse / expand tree node"],
  ["o · ↵", "open selected tree node"],
  ["[ · ]", "previous / next page in the register"],
  ["{ · }", "previous / next tab"],
  ["x", "close current tab"],
  ["?", "this help"],
  ["esc", "close overlays, leave the composer"],
];

export default function HelpOverlay({ onClose }: { onClose: () => void }) {
  return (
    <div className="overlay-backdrop" onMouseDown={onClose}>
      <div
        className="help"
        role="dialog"
        aria-label="Keyboard shortcuts"
        onMouseDown={(e) => e.stopPropagation()}
      >
        <h2>Keys</h2>
        <table>
          <tbody>
            {BINDINGS.map(([keys, action]) => (
              <tr key={keys}>
                <td className="keys">{keys}</td>
                <td>{action}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <p className="help-note">
          Pages generated by <code>uv run python -m tools.lingua</code>.
        </p>
      </div>
    </div>
  );
}
