"""Render chapter and dimension pages (Markdown) under devenv/reference/<name>/<vN>/pages/."""

from pathlib import Path

import yaml

from . import dimensions
from .model import Chapter, Corpus
from .status import RegisterBundle, state_summary
from .translation import mode_status

GENERATED_NOTE = (
    "<!-- Generated by `./ch` (build) — do not edit by hand. The linguistic "
    "structure lives in devenv/reference/<corpus>/<vN>/data/*.yaml, which is "
    "machine-owned: written only by `./ch author --apply` and `./ch set`, "
    "authored via /ch:translate. -->"
)

# Register-wide page filename per dimension, under pages/.
PAGE_FILENAMES = {
    "lexicon": "lexicon.md",
    "phrasebook": "phrasebook.md",
    "concept-relations": "relations.md",
}

MAX_SOURCE_LINES = 20


def dimension_page_relpath(corpus: Corpus, slug: str) -> str:
    return f"{corpus.name}/{corpus.register}/pages/{PAGE_FILENAMES[slug]}"


def index_relpath(corpus: Corpus) -> str:
    return f"{corpus.name}/{corpus.register}/pages/README.md"


def _frontmatter(chapter: Chapter, corpus: Corpus, states: dict[str, str]) -> str:
    fm: dict = {
        "id": chapter.id,
        "corpus": chapter.corpus,
        "register": chapter.register,
        "group": chapter.group,
        "group_label": chapter.group_label,
        "number": chapter.number,
        "slug": chapter.slug,
        "title": chapter.title,
    }
    if chapter.description:
        fm["description"] = chapter.description
    fm["kind"] = chapter.kind
    fm["content_hash"] = chapter.content_hash
    fm["states"] = dict(states)
    if chapter.source_url:
        fm["source_url"] = chapter.source_url
    fm["source_checkout"] = corpus.checkout
    body = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, width=1000)
    return f"---\n{body}---"


def _callout(chapter: Chapter, states: dict[str, str]) -> list[str]:
    items = []
    for slug, state in states.items():
        label = dimensions.REGISTRY[slug].LABEL
        if state == "none":
            items.append(
                f"**{label}:** nothing extracted for this chapter yet. "
                f"Run `/ch:translate {chapter.id}`."
            )
        elif state == "stale":
            items.append(
                f"**{label}:** the chapter changed since these entries were "
                f"anchored. Re-author via `/ch:translate {chapter.id}`, or "
                f"review and run `./ch accept-drift {chapter.id} "
                f"--dimension {slug}`."
            )
    if not items:
        return []
    return ["> [!WARNING]", *(f"> - {item}" for item in items), ""]


def _term_line(slug: str, entry: dict) -> str:
    line = f"- **{entry['term']}** (`{slug}`, {entry['kind']}) — {entry['definition']}"
    if entry.get("aliases"):
        line += f" *Also known as: {', '.join(entry['aliases'])}.*"
    return line


def _chapter_markdown(chapter: Chapter, bundle: RegisterBundle) -> str:
    corpus = bundle.corpus
    states = bundle.chapter_states(chapter)
    local = chapter.local_id
    out = [_frontmatter(chapter, corpus, states), GENERATED_NOTE, ""]

    out += [f"# {chapter.title}", ""]
    meta = [f"**{chapter.group_label}** · Chapter {chapter.number}"]
    if chapter.kind == "code":
        meta.append(f"Code unit · {len(chapter.unit_paths)} files")
    out += [" · ".join(meta), ""]
    if chapter.description:
        out += [f"*{chapter.description}*", ""]

    out += _callout(chapter, states)

    if "lexicon" in bundle.tracked_modes:
        lexmod = dimensions.REGISTRY["lexicon"]
        lexicon = bundle.data["lexicon"]
        defined = lexmod.terms_defined(lexicon, local)
        mentioned = lexmod.terms_mentioned(lexicon, local)
        out += ["## Terms defined here", ""]
        if defined:
            out += [_term_line(slug, lexicon[slug]) for slug in defined]
        else:
            out.append("No terms defined by this chapter yet.")
        out.append("")
        if mentioned:
            out += ["## Terms mentioned", ""]
            out += [
                f"- **{lexicon[slug]['term']}** (`{slug}`) — defined in "
                f"{lexicon[slug]['defined_in']}"
                for slug in mentioned
            ]
            out.append("")

    if "phrasebook" in bundle.tracked_modes:
        phrases = dimensions.REGISTRY["phrasebook"].entries_for_chapter(
            bundle.data["phrasebook"], local)
        if phrases:
            out += ["## Phrasings grounded here", ""]
            for slug, entry in sorted(phrases.items()):
                out += [f"### {entry['phrase']}", "",
                        f"*Intent:* {entry['intent']}", ""]
                if entry.get("template"):
                    out += ["```text", entry["template"], "```", ""]
                out += ["Terms: " + ", ".join(f"`{t}`" for t in entry["terms"]), ""]

    if "concept-relations" in bundle.tracked_modes:
        edges = dimensions.REGISTRY["concept-relations"].entries_for_chapter(
            bundle.data["concept-relations"], local)["edges"]
        if edges:
            out += ["## Relations", ""]
            out += [
                f"- **{e['from']}** —{e['type']}→ **{e['to']}**: {e['gloss']}"
                for e in edges
            ]
            out.append("")

    out += ["## Sources", ""]
    rels = [p.relative_to(corpus.root).as_posix() for p in chapter.unit_paths]
    if chapter.source_url:
        out.append(f"- Upstream: [{chapter.source_url.removeprefix('https://')}]"
                   f"({chapter.source_url})")
    for rel in rels[:MAX_SOURCE_LINES]:
        out.append(f"- `source/{rel}`")
    if len(rels) > MAX_SOURCE_LINES:
        out.append(f"- … and {len(rels) - MAX_SOURCE_LINES} more files")
    out.append("")

    return "\n".join(out).rstrip() + "\n"


def _table_cell(text: str) -> str:
    return text.replace("|", "\\|")


def _index_markdown(bundle: RegisterBundle) -> str:
    """Per-register index at devenv/reference/<name>/<vN>/pages/README.md; links are
    relative to that file. The cross-corpus overview is the web viewer's index."""
    corpus = bundle.corpus
    chapters = corpus.chapters
    label = f": {corpus.label}" if corpus.label else ""
    modes = " · ".join(
        m + ("" if mode_status(m) == "implemented" else " (recorded — not yet implemented)")
        for m in corpus.modes
    )
    totals = bundle.totals()
    totals_line = " · ".join(f"{n} {noun}" for noun, n in totals.items())
    out = [
        f"# {corpus.title} — {corpus.register}{label}",
        "",
        GENERATED_NOTE,
        "",
        f"{len(chapters)} chapters" + (f" · {totals_line}" if totals_line else "") + ".",
        "",
    ]
    if modes:
        out += [f"Translation modes: {modes}.", ""]
    dimension_links = [
        f"[{dimensions.REGISTRY[slug].LABEL}]({PAGE_FILENAMES[slug]})"
        for slug in bundle.tracked_modes
    ]
    if dimension_links:
        out += [" · ".join(dimension_links), ""]
    columns = [dimensions.REGISTRY[s].LABEL for s in bundle.tracked_modes]
    for group in corpus.groups:
        group_chapters = [c for c in chapters if c.group == group.id]
        if not group_chapters:
            continue
        out += [
            f"## {group.label}",
            "",
            "| # | Chapter | " + " | ".join(columns) + " |",
            "|---|---------|" + "|".join("---" for _ in columns) + "|",
        ]
        for c in group_chapters:
            states = bundle.chapter_states(c)
            cells = " | ".join(states[s] for s in bundle.tracked_modes)
            out.append(
                f"| {c.number} "
                f"| [{_table_cell(c.title)}]({c.group}/{c.slug}.md) "
                f"| {cells} |"
            )
        out.append("")
    out += [
        f"*Generated by `./ch` from "
        f"{corpus.name}/{corpus.register}@{corpus.checkout}.*",
        "",
    ]
    return "\n".join(out)


def _chapters_list(anchors: list[dict]) -> str:
    return ", ".join(sorted({a["chapter"] for a in anchors}))


def _lexicon_markdown(bundle: RegisterBundle) -> str:
    corpus = bundle.corpus
    data = bundle.data["lexicon"]
    out = [
        f"# {corpus.title} — Lexicon ({corpus.register})",
        "",
        GENERATED_NOTE,
        "",
        f"{len(data)} terms — what things are called in this corpus.",
        "",
    ]
    for slug, entry in sorted(data.items()):
        out += [f"### {entry['term']} (`{slug}`)", ""]
        out.append(f"*{entry['kind']}* — {entry['definition']}")
        out.append("")
        if entry.get("aliases"):
            out += [f"Also known as: {', '.join(entry['aliases'])}.", ""]
        out += [
            f"Defined in {entry['defined_in']} · "
            f"anchored in: {_chapters_list(entry['anchors'])}",
            "",
        ]
    return "\n".join(out).rstrip() + "\n"


def _phrasebook_markdown(bundle: RegisterBundle) -> str:
    corpus = bundle.corpus
    data = bundle.data["phrasebook"]
    out = [
        f"# {corpus.title} — Phrasebook ({corpus.register})",
        "",
        GENERATED_NOTE,
        "",
        f"{len(data)} phrasings — how to say it when instructing an agent "
        f"about this corpus.",
        "",
    ]
    for slug, entry in sorted(data.items()):
        out += [f"### {entry['phrase']}", "",
                f"*Intent:* {entry['intent']}", ""]
        if entry.get("template"):
            out += ["```text", entry["template"], "```", ""]
        out += [
            "Terms: " + ", ".join(f"`{t}`" for t in entry["terms"]),
            "",
            f"Grounded in: {_chapters_list(entry['anchors'])}",
            "",
        ]
    return "\n".join(out).rstrip() + "\n"


def _relations_markdown(bundle: RegisterBundle) -> str:
    corpus = bundle.corpus
    edges = bundle.data["concept-relations"]["edges"]
    lexicon = bundle.data.get("lexicon", {})
    out = [
        f"# {corpus.title} — Concept relations ({corpus.register})",
        "",
        GENERATED_NOTE,
        "",
        f"{len(edges)} typed links between lexicon terms.",
        "",
    ]
    by_from: dict[str, list[dict]] = {}
    for edge in edges:
        by_from.setdefault(edge["from"], []).append(edge)
    for slug in sorted(by_from):
        term = lexicon.get(slug, {}).get("term", slug)
        out += [f"### {term} (`{slug}`)", ""]
        out += [
            f"- —{e['type']}→ **{e['to']}**: {e['gloss']} "
            f"({_chapters_list(e['anchors'])})"
            for e in by_from[slug]
        ]
        out.append("")
    return "\n".join(out).rstrip() + "\n"


_DIMENSION_RENDERERS = {
    "lexicon": _lexicon_markdown,
    "phrasebook": _phrasebook_markdown,
    "concept-relations": _relations_markdown,
}


def render_all(
    bundles: list[RegisterBundle],
    out_dir: Path,
    only: set[str] | None = None,
) -> list[Path]:
    written: list[Path] = []
    for bundle in bundles:
        corpus = bundle.corpus
        for chapter in corpus.chapters:
            if only and chapter.id not in only:
                continue
            page = out_dir / chapter.page_relpath
            page.parent.mkdir(parents=True, exist_ok=True)
            page.write_text(_chapter_markdown(chapter, bundle))
            written.append(page)

        for slug in bundle.tracked_modes:
            page = out_dir / dimension_page_relpath(corpus, slug)
            page.parent.mkdir(parents=True, exist_ok=True)
            page.write_text(_DIMENSION_RENDERERS[slug](bundle))
            written.append(page)

        index = out_dir / index_relpath(corpus)
        index.parent.mkdir(parents=True, exist_ok=True)
        index.write_text(_index_markdown(bundle))
        written.append(index)
    return written
