import type { Metadata } from "next";
import { getManifest } from "@/lib/content";
import "./globals.css";

export const metadata: Metadata = {
  title: "chiron",
  description:
    "The lexicon, phrasebook, and concept relations of each mounted corpus.",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const manifest = await getManifest().catch(() => null);
  const versions = manifest?.corpora
    .map((s) => `${s.name}/${s.register}@${s.checkout}`)
    .join(", ");
  return (
    <html lang="en">
      <body>
        <div className="page">
          {children}
          <footer className="site-footer">
            Generated by <code>uv run python -m tools.lingua</code>
            {versions ? <> from {versions}</> : null}
          </footer>
        </div>
      </body>
    </html>
  );
}
